---
- hosts: all
  gather_facts: yes

  pre_tasks:
    - name: Update Apt Cache
      apt: update_cache=yes cache_valid_time=86400
      when: ansible_os_family == "Debian"
  roles:
    - { role: geerlingguy.nginx }
